name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up npm7
      run: npm i -g npm@7
    - name: npm install, build
      run: |
        npm ci
        npm run build --if-present
    - name: npm test
      run: |
        npm test
    - name: check webpack build
      run: |
        bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes in webpack build' && git status && exit 1 )"
      env:
        CI: true
